version: '3'

volumes:
  database-data:
  mysql-socket:

services:
  web:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - '.:/var/www/myspot'
      - 'mysql-socket:/tmp/sockets'
    command: sh -c "bundle exec rails db:migrate && bundle exec rails s -b 0.0.0.0"
    tty: true
    stdin_open: true
    depends_on:
      - db
  
  db:
    image: mariadb
    volumes:
      - 'database-data:/var/lib/mysql'
      - 'mysql-socket:/var/run/mysqld'
    ports:
      - '3306:3306'
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_PASSWORD: ''
      MYSQL_USER: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"